[package]
name = "nbx-shaders-build"
version.workspace = true
edition.workspace = true

[build-dependencies]
nbx-shaders-src = { workspace = true }

[features]
default = [
  # Comment this out to enable more optimal math
  # "emulate_extended_maths",
  # Comment this out to enable newer version of spirv (unsupported by wgpu)
  "spirv_1_3"
]
emulate_extended_maths = []
spirv_1_3 = []
