[package]
name = "nbx-miner"
publish = false
version.workspace = true
#edition.workspace = true
edition = "2021"

[features]
default = ["jemalloc"]
jemalloc = ["tikv-jemallocator"]
tracing-heap = ["tikv-jemallocator", "tracy-client"]
gpu = ["nbx-jetpack/gpu-prod"]
# Disables logging in most places
stealthy = ["nbx-jetpack/stealthy"]
# Enables --miner-tls-key,--miner-tls-chain arguments, that enable setting up non-embedded TLS keys for auth
server-tls-key-load = []
# Enables prometheus exporter http server
prom-exporter = ["metrics-exporter-prometheus", "metrics-util"]
# Enables client module, which is necessary for the client binary
client = ["kernels/miner"]
# Enables server-based verification, and proxy difficulty adjustments
verifier = ["kernels/verifier"]
# Forces the server pre-verify the proofs. Mandatory for pool setups
force-preverify = ["verifier"]
# Enable NBX_JWT_KEY[1-9] environment variable reading, which configures client authentication
jwt-auth-server = []
# Enable NBX_AUTH_JWT environment variable reading, which configures client authentication
jwt-auth-client = []
# Enable --miner-save-attempts command line option
miner-save-attempts = []
# Enable database driven share submission/ban list/etc.
db = ["sqlx", "serde_json", "force-preverify"]
# Enable sqlite db for testing
db-sqlite = ["sqlx?/sqlite"]

[[bin]]
name = "nbx-proxy"

[[bin]]
name = "nbx-miner"
required-features = ["client"]

[dependencies]
kernels = { workspace = true, features = [] }
nockapp.workspace = true
nockvm.workspace = true
nockvm_macros.workspace = true
bitvec.workspace = true
either.workspace = true

clap.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-test.workspace = true
anyhow.workspace = true
flume.workspace = true
rand = { workspace = true }
tikv-jemallocator = { workspace = true, optional = true }
gdt-cpus.workspace = true
nockchain-libp2p-io.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
bincode.workspace = true
strum.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
tokio-rustls.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
x509-parser.workspace = true
metrics.workspace = true
metrics-exporter-prometheus = { workspace = true, optional = true }
metrics-util = { workspace = true, optional = true }
ibig.workspace = true
sha3.workspace = true
jsonwebtoken.workspace = true
webpki-roots.workspace = true
sysinfo.workspace = true
chacha.workspace = true
itertools.workspace = true
uuid = { workspace = true, features = ["serde"] }
sqlx = { workspace = true, optional = true, features = ["postgres", "tls-rustls", "runtime-tokio", "uuid"] }
serde_json = { workspace = true, optional = true }
toml.workspace = true

zkvm-jetpack.workspace = true
nbx-jetpack.workspace = true
tracy-client = { workspace = true, optional = true }
