[package]
name = "nbx-miner"
publish = false
version.workspace = true
#edition.workspace = true
edition = "2021"

[features]
default = ["jemalloc"]
jemalloc = ["tikv-jemallocator"]
tracing-heap = ["tikv-jemallocator", "tracy-client"]
gpu = ["nbx-jetpack/gpu-prod"]
stealthy = ["force-tls", "nbx-jetpack/stealthy"]
force-tls = []
prom-exporter = ["metrics-exporter-prometheus", "metrics-util"]
client = ["kernels/miner"]
verifier = ["kernels/verifier"]
force-preverify = ["verifier"]
force-send-only-targets = []

[[bin]]
name = "nbx-proxy"
required-features = ["verifier"]

[[bin]]
name = "nbx-miner"
required-features = ["client"]

[dependencies]
kernels = { workspace = true, features = [] }
nockapp.workspace = true
nockvm.workspace = true
nockvm_macros.workspace = true
bitvec.workspace = true
either.workspace = true

clap.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-test.workspace = true
anyhow.workspace = true
flume.workspace = true
rand = { workspace = true }
tikv-jemallocator = { workspace = true, optional = true }
gdt-cpus.workspace = true
nockchain-libp2p-io.workspace = true
serde.workspace = true
bincode.workspace = true
strum.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
tokio-rustls.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
x509-parser.workspace = true
metrics.workspace = true
metrics-exporter-prometheus = { workspace = true, optional = true }
metrics-util = { workspace = true, optional = true }
ibig.workspace = true
sha3.workspace = true
jsonwebtoken.workspace = true

zkvm-jetpack.workspace = true
nbx-jetpack.workspace = true
tracy-client = { workspace = true, optional = true }
