
[profile.release.package."wgpu-hal"]
debug-assertions = true

[profile.release-v4]
inherits = "release"
rustflags = ["-C", "target-cpu=x86-64-v4"]
opt-level = 3
lto = "thin"

[profile.release-v3]
inherits = "release-v4"
rustflags = ["-C", "target-cpu=x86-64-v3"]

[profile.release-native]
inherits = "release-v4"
rustflags = ["-C", "target-cpu=native"]#, "-C", "force-frame-pointers=yes"]
