
[profile.release-debug]
inherits = "release"
rustflags = ["-C", "force-frame-pointers=yes"]

[profile.release-debug.package."wgpu-hal"]
debug-assertions = true

[profile.release-strip]
inherits = "release"
strip = "symbols"

[profile.release-v4]
inherits = "release"
rustflags = ["-C", "target-cpu=x86-64-v4"]
opt-level = 3
lto = "thin"

[profile.release-v4-strip]
inherits = "release-v4"
strip = "symbols"
panic = "abort"

[profile.release-v3]
inherits = "release-v4"
rustflags = ["-C", "target-cpu=x86-64-v3"]

[profile.release-v3-strip]
inherits = "release-v3"
strip = "symbols"
panic = "abort"

[profile.release-native]
inherits = "release-v4"
rustflags = ["-C", "target-cpu=native"]
