[package]
name = "nockchain-metrics-exporter"
version.workspace = true
edition.workspace = true

[dependencies]
nockapp = { workspace = true }
nockvm = { workspace = true }
nockapp-grpc = { workspace = true, features = ["client"] }
nockapp-grpc-proto = { workspace = true, features = ["client"] }
nockvm_macros = { workspace = true }

bardecoder = { workspace = true }
clap = { workspace = true, features = ["derive"] }
either.workspace = true
getrandom.workspace = true
image = { workspace = true }
tempfile.workspace = true
termimad.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow.workspace = true
metrics.workspace = true
metrics-util.workspace = true
metrics-exporter-prometheus.workspace = true
gnort.workspace = true
ibig.workspace = true
