[package]
name = "nbx-jetpack"
version.workspace = true
edition.workspace = true

[features]
default = []
gpu = ["nbx-shaders", "pollster", "wgpu", "naga"]
gpu-prod = ["gpu", "nbx-shaders/comptime", "spirv_passthrough"]
stealthy = []
spirv_passthrough = ["nbx-shaders/spirv_passthrough"]
validate-gpu = ["gpu"]

[dependencies]
nockvm.workspace = true
nockvm_macros.workspace = true
nockapp.workspace = true
zkvm-jetpack.workspace = true
either.workspace = true
num-traits.workspace = true
tracing.workspace = true
ibig.workspace = true

array-concat.workspace = true
array-util.workspace = true
const_for.workspace = true
rayon.workspace = true
tokio.workspace = true
bytemuck.workspace = true
nbx-tip5.workspace = true

pollster = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
naga = { workspace = true, optional = true }
nbx-shaders = { workspace = true, optional = true }

