[package]
name = "nbx-jetpack"
version.workspace = true
edition.workspace = true

[features]
default = ["codefuscate"]
gpu = ["nbx-shaders", "pollster", "wgpu", "naga"]
gpu-prod = ["gpu", "nbx-shaders/comptime", "shader_passthrough"]
stealthy = ["tracing/stealthy", "codefuscate"]
shader_passthrough = ["nbx-shaders/shader_passthrough"]
validate-gpu = ["gpu"]
codefuscate = []

[dependencies]
nockvm.workspace = true
nockvm_macros.workspace = true
nockapp.workspace = true
zkvm-jetpack.workspace = true
either.workspace = true
num-traits.workspace = true
tracing.workspace = true
ibig.workspace = true

array-concat.workspace = true
array-util.workspace = true
const_for.workspace = true
tokio.workspace = true
bytemuck.workspace = true
nbx-tip5.workspace = true
rayon.workspace = true
goldberg.workspace = true
obfstr.workspace = true

pollster = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
naga = { workspace = true, optional = true }
nbx-shaders = { workspace = true, optional = true }

[lints.clippy]
disallowed-types = "deny"
disallowed-macros = "deny"
disallowed-methods = "deny"
