[package]
name = "tracing"

[dependencies]
tracing-base.workspace = true
noop-attr = { workspace = true, optional = true }

[features]
attributes = ["tracing-base/attributes"]
default = ["std", "attributes"]
stealthy = ["noop-attr", "tracing-base/max_level_off", "tracing-base/release_max_level_off"]
std = ["tracing-base/std"]
